---
# handlers file for bastion
- name: Regen GRUB
  ansible.builtin.shell: grub-mkconfig -o /boot/grub/grub.cfg
- name: Reload keyboard
  ansible.builtin.service:
    name: keyboard-setup
    state: restarted